### PR TITLE
Teardown

### PR DESCRIPTION
**Pull request by evabanegacom**
This is the design teardown project.
It is about showing the heatmap of  www.smashingmagazine.com
It is a collaborative project.
We built it in greyscale.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @evabanegacom and @Samitti 
### You guys have done great so far :clap: However, you have a few issues to work on before your project could be approved.
- Initialize stickler to your [github repo](https://github.com/microverseinc/linters-config/tree/master/css)
- The section on smashing members should be 3 columns
3 columns
- It is advisable to always use html5 semantic tags like section, article, aside, footer, nav, main
### Make these changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by evabanegacom** [comment]
Bros, this is a dynamic website they appearance is different on different
visits or clicks. on my computer, the smashing members shows just two,

**Comment by evabanegacom** [comment]
I have used the necessary HTML semantics and stickler is working just fine.
This is a dynamic website, the views change by every click with respect to time. 
They are not always exactly the same.

**Review by rOluochKe — APPROVED** [review]
Hello Team
### Congratulations :boom: :100: your project has been approved.
### You can merge and submit the project from your dashboard. Good luck with the next project.
- Happy coding!

**Comment by evabanegacom** [comment]
thank you

**Pull request merged**
